# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@1
  displayName: Install .NET Core 3.0 SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview7-012821'

- task: UseDotNet@2
  displayName: Install .NET Core 2.2 SDK
  inputs:
    packageType: 'sdk'
    version: '2.2.401'

- script: |
    dotnet tool install ElectronNET.CLI -g
  displayName: 'Install global tool ElectronNET.CLI'

- script: |
    echo $PWD
    mkdir -p FotoManager/obj/desktop/win
    echo $PWD
    cd FotoManager/obj/desktop/win
    echo $PWD
    sudo npm install electron-builder --global
    echo $PWD
    cd /../../../..
    echo $PWD
  displayName: 'Install global tool electron-builder'

- script: |
    echo $PWD
    cd FotoManager
    echo $PWD
    ls
    electronize build /target win
  displayName: 'Build Windows app with ElectronNET'