# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreInstaller@1
  displayName: Install .NET Core 3.0 SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.100'

- task: UseDotNet@2
  displayName: Install .NET Core 2.2 SDK
  inputs:
    packageType: 'sdk'
    version: '2.2.401'

- script: |
    dotnet tool install ElectronNET.CLI -g
  displayName: 'Install global tool ElectronNET.CLI'

- script: |
    cd FotoManager
    electronize build /target win
  displayName: 'Build Windows app with ElectronNET'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Tests/Tests.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    publishTestResults: true
- task: reportgenerator@4
  inputs:
    reports: '**/coverage.cobertura.xml'
    targetdir: 'CoverageReport'
  displayName: 'Refactor coverage report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coverage.cobertura.xml'
    reportDirectory: 'CoverageReport'
  displayName: 'Publish code coverage results'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: FotoManager/bin/Desktop
    artifactName: 'App'
  displayName: 'Publish build artifact'