name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching everything, e. g. "v1" or "2021.2.2.1"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    - name: Install global tool ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI -g
    - name: Restore dependencies
      run: dotnet restore FotoManager.sln
    - name: Build
      run: dotnet build --no-restore FotoManager.sln
    - name: Test
      run: dotnet test --no-build FotoManager.sln /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[*]FotoManager.Pages.*%2c[*]FotoManager.Startup"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.10
      with:
        reports: 'Tests\coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'Badges'
        verbosity: 'Info'
        tag: '${{ github.ref_name }}'
        toolpath: 'reportgeneratortool'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: CoverageReport       
        path: coveragereport\badge_combined.svg
    - name: Build Windows app with ElectronNET
      run: |
        cd FotoManager
        electronize build /target win
    - name: Copy packed executable to separate location
      run: |
        mkdir FotoManager\Release
        copy FotoManager\bin\Desktop\FotoFlipper*.exe FotoManager\Release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: FotoManager\Release\*
        tag_name: ${{ github.ref_name }}