name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching everything, e. g. "v1" or "2021.2.2.1"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - name: Install global tool ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI -g
    - name: Restore dependencies
      run: dotnet restore FotoManager.sln
    - name: Build
      run: dotnet build --no-restore FotoManager.sln
    - name: Test
      run: dotnet test --no-build FotoManager.sln
    - name: Build Windows app with ElectronNET
      run: |
        pushd FotoManager
        electronize build /target win
        popd
    - name: Copy packed executable to separate location
      run: |
        mkdir FotoManager\Release
        copy FotoManager\bin\Desktop\FotoFlipper*.exe FotoManager\Release
        ls Fotomanager\Release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: FotoManager\Release\*
        tag_name: ${{ github.ref_name }}